# realesrgan_enhancer.py
# This script uses the powerful Real-ESRGAN model to enhance general-purpose images.
# It now includes a post-processing sharpening step for extra clarity.

import cv2
import os
import torch
from realesrgan import RealESRGANer
from basicsr.archs.rrdbnet_arch import RRDBNet
import sys
from tqdm import tqdm
import numpy as np

# --- HARDCODED PATHS ---
input_folder = r"C:\Users\Aastha sengar\Desktop\final-deepfake\sorted_dataset\fake"
output_folder = r"C:\Users\Aastha sengar\Desktop\final-deepfake\fake_enhanced_realesrgan_with_extra"
model_name = 'RealESRGAN_x4plus.pth'


def main():
    """Main function to process images using the Real-ESRGAN model."""

    print("Setting up the Real-ESRGAN model...")
    # The 'realesrgan' library automatically handles model downloads.
    # This might take a moment on the first run.
    try:
        # Define the model architecture that matches the .pth file
        model = RRDBNet(num_in_ch=3, num_out_ch=3, num_feat=64, num_block=23, num_grow_ch=32, scale=4)
        
        # Initialize the RealESRGANer
        upsampler = RealESRGANer(
            scale=4,
            model_path=model_name, # The library will download this to a cache
            model=model,
            tile=0,
            tile_pad=10,
            pre_pad=0,
            half=torch.cuda.is_available() # Use GPU if available
        )
        print("Real-ESRGAN model loaded successfully.")
    except Exception as e:
        print(f"--- CRITICAL ERROR ---")
        print(f"Could not initialize the Real-ESRGAN model: {e}")
        print("Please ensure you have a working internet connection for the first run.")
        return

    # --- FOLDER AND FILE PROCESSING ---
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)
        print(f"Created output directory: {output_folder}")

    supported_extensions = ('.png', '.jpg', '.jpeg', '.bmp', '.tif', '.tiff')
    image_files = [f for f in os.listdir(input_folder) if f.lower().endswith(supported_extensions)]

    if not image_files:
        print(f"No supported image files found in '{input_folder}'.")
        return

    print(f"\nFound {len(image_files)} images to process...")

    for filename in tqdm(image_files, desc="Enhancing images"):
        input_path = os.path.join(input_folder, filename)
        base_name, extension = os.path.splitext(filename)

        try:
            image = cv2.imread(input_path, cv2.IMREAD_UNCHANGED)
            if image is None:
                print(f"Warning: Could not read {filename}. Skipping.")
                continue
            
            # Step 1: Enhance the image using the upsampler
            output_image, _ = upsampler.enhance(image, outscale=4)
            
            if output_image is not None:
                # Step 2: NEW - Apply a multi-stage post-processing pipeline for maximum clarity

                # Stage 2a: Sharpening (Unsharp Mask)
                # This makes the details generated by the AI model pop a bit more.
                gaussian_blur = cv2.GaussianBlur(output_image, (0, 0), 3)
                sharpened_image = cv2.addWeighted(output_image, 1.5, gaussian_blur, -0.5, 0)

                # Stage 2b: Denoising
                # Gently removes any subtle noise that might have been introduced during upscaling.
                denoised_image = cv2.fastNlMeansDenoisingColored(sharpened_image, None, 10, 10, 7, 21)

                # Stage 2c: Contrast Enhancement (CLAHE)
                # Improves local contrast, making features stand out without over-saturating the image.
                lab = cv2.cvtColor(denoised_image, cv2.COLOR_BGR2LAB)
                l, a, b = cv2.split(lab)
                clahe = cv2.createCLAHE(clipLimit=3.0, tileGridSize=(8, 8))
                cl = clahe.apply(l)
                limg = cv2.merge((cl, a, b))
                final_image = cv2.cvtColor(limg, cv2.COLOR_LAB2BGR)

                # Save the final, enhanced image
                output_filename = f"{base_name}_enhanced{extension}"
                output_path = os.path.join(output_folder, output_filename)
                cv2.imwrite(output_path, final_image)
            else:
                 print(f"Warning: Could not enhance {filename}. Skipping.")

        except Exception as e:
            print(f"An error occurred while processing {filename}: {e}")

    print("\nProcessing complete.")
    print(f"All enhanced images have been saved to: {output_folder}")


if __name__ == "__main__":
    main()

